config/routes.rb
Ilohv::Engine.routes.draw do
  root to: 'directories#index'

  require 'ilohv/routing_constraint/file'
  require 'ilohv/routing_constraint/directory'
  get '*path' => 'directories#show', constraints: Ilohv::RoutingConstraint::Directory.new
  get '*path' => 'files#show', constraints: Ilohv::RoutingConstraint::File.new

  resources :directories, except: :index
  resources :files, except: :index
end

app/models/ilohv/directory.rb
module Ilohv
  class Directory < Node
    def directories
      children.where(type: 'Ilohv::Directory')
    end

    def files
      children.where(type: 'Ilohv::File')
    end
  end
end

app/models/ilohv/file.rb
module Ilohv
  class File < Node
    mount_uploader :file, FileUploader

    store :meta_data, accessors: [:content_type, :size, :original_filename, :extension]

    validates :file, presence: true
    validates :file_token, presence: true, uniqueness: { allow_blank: true }

    before_validation :calculate_name, prepend: true
    before_validation :extract_meta_data, prepend: true, if: -> { file.present? && file_changed? }
    before_validation :generate_file_token, on: :create

    delegate :url, to: :file

    private

    def calculate_name
      self.name = original_filename if name.blank?
    end

    def extract_meta_data
      self.content_type = file.file.content_type
      self.size = file.file.size
      self.original_filename = file.file.original_filename
      self.extension = ::File.extname(file.file.original_filename)[1..-1]
    end

    def generate_file_token
      self.file_token = SecureRandom.uuid
    end

  end
end

app/models/ilohv/node.rb
require_dependency 'ancestry'
require_dependency 'babosa'

module Ilohv
  class Node < ActiveRecord::Base
    has_ancestry

    validates :name, presence: true
    validate :require_unique_path

    default_scope -> { order("name ASC") }

    before_validation :calculate_full_path

    def slug
      return unless name.present?

      # reproducing babosa's #normalize! without cleaning non-word characters because we need the . in filenames
      slug = name.dup.to_identifier
      slug.transliterate!
      slug.clean!
      slug.downcase!
      slug.with_separators!

      slug
    end

    def other_with_same_path?
      scope = self.class.where(full_path: full_path)
      scope = scope.where.not(id: id) if persisted?
      scope.any?
    end

    private

    def calculate_full_path
      self.full_path = [parent_full_path, slug].compact.join('/')
    end

    def parent_full_path
      parent.try(:full_path)
    end

    def require_unique_path
      errors.add(:name, :taken) if other_with_same_path?
    end

  end
end

app/controllers/ilohv/application_controller.rb
module Ilohv
  class ApplicationController < Ilohv.parent_controller.constantize
    private

    def ilohv_path(path)
      "#{Ilohv::Engine.config.url_root}/#{path}"
    end
    helper_method :ilohv_path

    def redirect_to_parent_or_index(node, options)
      redirect_to node.parent ? ilohv_path(node.parent.full_path) : root_path, options
    end
  end
end

app/controllers/ilohv/directories_controller.rb
require_dependency 'ilohv/application_controller'

module Ilohv
  class DirectoriesController < ApplicationController
    before_action :set_directory, only: [:show, :edit, :update, :destroy]
    before_action :build_directory, only: [:new, :create]
    before_action :set_include_subdirectories, only: [:index, :show]

    def index
      @directories = Directory.roots
    end

    def show
    end

    def new
    end

    def edit
    end

    def create
      @directory.assign_attributes(directory_params)

      if @directory.save
        redirect_to_parent_or_index(@directory, notice: 'Directory was successfully created.')
      else
        render :new
      end
    end

    def update
      if @directory.update(directory_params)
        redirect_to_parent_or_index(@directory, notice: 'Directory was successfully updated.')
      else
        render :edit
      end
    end

    def destroy
      @directory.destroy
      redirect_to_parent_or_index(@directory, notice: 'Directory was successfully deleted.')
    end

    private

    def set_directory
      @directory = params[:id].present? ? Directory.find(params[:id]) : Directory.find_by_full_path(params[:full_path])
    end

    def build_directory
      scope = params[:parent_id].present? ? Directory.find(params[:parent_id]).directories : Directory
      @directory = scope.new(type: 'Ilohv::Directory')
    end

    def directory_params
      params[:directory] ||= {}
      params[:directory].permit(:name)
    end

    def set_include_subdirectories
      @include_subdirectories = params[:include_subdirectories]
    end
  end
end

app/controllers/ilohv/files_controller.rb
require_dependency 'ilohv/application_controller'

module Ilohv
  class FilesController < ApplicationController
    before_action :set_file, only: [:show, :edit, :update, :destroy]
    before_action :build_file, only: [:new, :create]

    def show
      send_data @file.file.read, content_type: @file.content_type
    end

    def new
    end

    def edit
    end

    def create
      @file.assign_attributes(file_params)

      if @file.save
        redirect_to_parent_or_index(@file, notice: 'File was successfully created.')
      else
        render :new
      end
    end

    def update
      if @file.update(file_params)
        redirect_to_parent_or_index(@file, notice: 'File was successfully updated.')
      else
        render :edit
      end
    end

    def destroy
      @file.destroy
      redirect_to_parent_or_index(@file, notice: 'File was successfully deleted.')
    end

    private

    def set_file
      @file = params[:id].present? ? File.find(params[:id]) : File.find_by_full_path(params[:full_path])
    end

    def build_file
      scope = params[:parent_id].present? ? Directory.find(params[:parent_id]).files : File
      @file = scope.new(type: 'Ilohv::File')
    end

    def file_params
      params[:file] ||= {}
      params[:file].permit(:name, :file)
    end

  end
end

app/views/ilohv/directories/_directory.html.erb
<tr>
  <td></td>
  <td><%= link_to local_assigns[:directory_name] || directory.name, local_assigns[:directory_path] || ilohv_path(directory.full_path) %></td>
  <td></td>
  <td></td>
  <td>
    <%- if local_assigns[:directory].present? -%>
      <div class="btn-group btn-group-xs">
        <%= link_to 'Edit', edit_directory_path(directory), id: "edit-directory-#{directory.id}", class: 'btn btn-default' %>
        <%= link_to 'Delete', directory_path(directory), method: :delete, data: { confirm: 'Really delete? All subdirectories and files will be deleted as well.' }, id: "delete-directory-#{directory.id}", class: 'btn btn-danger' %>
      </div>
    <%- end -%>
  </td>
</tr>

app/views/ilohv/directories/_form.html.erb
<%= form_for(@directory, as: :directory, html: { class: 'form-horizontal' }) do |f| %>
  <% if @directory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@directory.errors.count, "error") %> prohibited this directory from being saved:</h2>

      <ul>
      <% @directory.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= hidden_field_tag :parent_id, @directory.parent_id %>
    <%= f.label :parent_id, 'Parent directory', class: 'col-lg-2 control-label' %>
    <div class="col-lg-10">
      <%= f.text_field :parent_id, value: @directory.parent.try(:full_path), class: 'form-control', disabled: true %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :name, class: 'col-lg-2 control-label' %>
    <div class="col-lg-10">
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit id: 'save-button', class: 'btn btn-primary' %> or
      <%= link_to 'cancel', @directory.parent ? ilohv_path(@directory.parent.path) : root_path %>
    </div>
  </div>
<% end %>

app/views/ilohv/directories/_list.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Current location:
    <ol class="breadcrumb current-location-breadcrumb">
      <li><%= link_to 'Home', root_path %></li>
      <%- if local_assigns[:directory].present? -%>
        <%- directory.ancestors.each do |directory| -%>
          <li><%= link_to directory.name, ilohv_path(directory.full_path) %></li>
        <%- end -%>
        <li class="active"><%= directory.name %></li>
      <%- end -%>
    </ol>
  </div>
  <div class="panel-body">
    <table class="table table-hover">
      <thead>
        <tr>
          <th></th>
          <th>Name</th>
          <th>Type</th>
          <th>Size</th>
          <th>
            <div class="btn-group btn-group-sm pull-right">
              <%= link_to new_directory_path(parent_id: local_assigns[:directory]), id: 'new-directory-button', class: 'btn btn-default' do %>
                <span class="glyphicon glyphicon-plus"></span> New directory
              <% end %>
              <%= link_to new_file_path(parent_id: local_assigns[:directory]), id: 'new-file-button', class: 'btn btn-default' do %>
                <span class="glyphicon glyphicon-upload"></span> New file
              <% end %>
            </div>
          </th>
        </tr>
      </thead>
      <tbody>
        <%- if local_assigns[:directory].present? -%>
          <%= render 'ilohv/directories/directory', directory_name: '..', directory_path: ilohv_path(directory.parent.try(:path)) %>
        <%- end -%>
        <%- if directories.present? || files.present? -%>
          <%= render partial: 'ilohv/directories/directory', collection: directories if directories.present? %>
          <%= render partial: 'ilohv/files/file', collection: files if files.present? %>
        <%- else -%>
          <tr>
            <td></td>
            <td colspan="4">This directory is currently empty.</td>
          </tr>
        <%- end -%>
      </tbody>
    </table>
  </div>
  <div class="panel-footer small">
    <%= link_to 'ilohv File Manager', 'https://github.com/clemens/ilohv' %> © 2014 Clemens Kofler. File type icons powered by <%= link_to 'Teambox Free file icons', 'https://github.com/teambox/Free-file-icons' %>.
  </div>
</div>

app/views/ilohv/directories/edit.html.erb
<h1>Editing directory</h1>

<%= render 'form' %>

app/views/ilohv/directories/index.html.erb
<%= render 'list', directories: @directories, files: [] %>

app/views/ilohv/directories/new.html.erb
<h1>New directory</h1>

<%= render 'form' %>

app/views/ilohv/directories/show.html.erb
<p id="notice"><%= notice %></p>

<%= render 'list', directory: @directory, directories: @directory.directories, files: @directory.files %>

app/views/ilohv/files/_file.html.erb
<tr>
  <td><%= image_tag("ilohv/file_types/#{file.extension}.png") %></td>
  <td><%= link_to file.name, ilohv_path(file.full_path) %></td>
  <td><%= file.content_type %></td>
  <td><%= number_to_human_size(file.size) %></td>
  <td>
    <div class="btn-group btn-group-xs">
      <%= link_to 'Edit', edit_file_path(file), id: "edit-file-#{file.id}", class: 'btn btn-default' %>
      <%= link_to 'Delete', file_path(file), method: :delete, data: { confirm: 'Really delete?' }, id: "delete-file-#{file.id}", class: 'btn btn-danger' %>
    </div>
  </td>
</tr>

app/views/ilohv/files/_form.html.erb
<%= form_for(@file, as: :file, html: { class: 'form-horizontal' }) do |f| %>
  <% if @file.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@file.errors.count, "error") %> prohibited this file from being saved:</h2>

      <ul>
      <% @file.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= hidden_field_tag :parent_id, @file.parent_id %>
    <%= f.label :parent_id, 'Directory', class: 'col-lg-2 control-label' %>
    <div class="col-lg-10">
      <%= f.text_field :parent_id, value: @file.parent.try(:full_path), class: 'form-control', disabled: true %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :name, class: 'col-lg-2 control-label' %>
    <div class="col-lg-10">
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :file, class: 'col-lg-2 control-label' %>
    <div class="col-lg-10">
      <%- if @file.file? -%>
        Current file: <%= File.basename(@file.file.path) %>
      <%- end -%>
      <%= f.hidden_field :file_cache %>
      <%= f.file_field :file, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit id: 'save-button', class: 'btn btn-primary' %> or
      <%= link_to 'cancel', @file.parent ? ilohv_path(@file.parent.path) : root_path %>
    </div>
  </div>
<% end %>

app/views/ilohv/files/edit.html.erb
<h1>Editing file</h1>

<%= render 'form' %>

app/views/ilohv/files/new.html.erb
<h1>New file</h1>

<%= render 'form' %>